// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd6s2QXnDz8ZHptai1drsojB7xYGT4FOk',
    appId: '1:215876160529:web:59c9a49defe85309dbf5b0',
    messagingSenderId: '215876160529',
    projectId: 'testnotify-83602',
    authDomain: 'testnotify-83602.firebaseapp.com',
    storageBucket: 'testnotify-83602.appspot.com',
    measurementId: 'G-JHE69ZNV07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5c8UrpVJZOo_sGc2rVkp2-SUh_xkAl5U',
    appId: '1:215876160529:android:7e07b15e3861148bdbf5b0',
    messagingSenderId: '215876160529',
    projectId: 'testnotify-83602',
    storageBucket: 'testnotify-83602.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABdKjfQibtneG8qRmzejOh1XodzbYpgOA',
    appId: '1:215876160529:ios:b489a92ebb384c74dbf5b0',
    messagingSenderId: '215876160529',
    projectId: 'testnotify-83602',
    storageBucket: 'testnotify-83602.appspot.com',
    iosClientId: '215876160529-gj8b4ccebksj397sia7g9m3ii3mud2s8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHomeWidget',
  );
}
